[[redirects]]
  from = "/rbr/*"
  status = 200
  to = "https://rocketbotroyale.winterpixel.io/:splat"
  force = false
[[redirects]]
  from = "/gd*"
  status = 200
  to = "https://gooberdash.winterpixel.io/:splat"
  force = false
